### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by mlieber** [drreddy/linkedin_public_profile_scraper#1]
hi,

how would you modify the code to return the result, instead of saving an output file ? 
Sorry i m not very familiar w/ Ruby ..
cheers,
Matt

**Comment by drreddy** [comment]
I don't clearly get your requirement. Do you want to just show the output to the console or do you want to pack this code into a function so that you pass a profile url to the function and the function will return the profile data.

**Comment by mlieber** [comment]
yes, sorry - the 2nd option. Pass a profile, and the function returns the profile data.

**Comment by drreddy** [comment]
Hello,
I have added a new folder called scraperClass in which a class for the scraper is available along with an example file. Can you check it and tell me if it satisfies your feature request, so that I can close this issue.

**Comment by mlieber** [comment]
Great Rajeev! I was writing it myself.
Thanks that solves it -
Matt

On Thu, Apr 16, 2015 at 12:01 AM, D. Rajeev. Reddy <notifications@github.com
